### ISSUE TITLE
BUGGGSSS

### ISSUE THREAD

**Issue by OveR1337XD** [overdodactyl/ShadowBird#1] opened 2018-08-06 18:58 UTC
So 60 version just released and I updated and I went for this dark theme and it have a lots of bugs.

Windows 10 x64
Thunderbird 60 x64
![bird343](https://user-images.githubusercontent.com/3746977/43735657-756cb664-99bb-11e8-9608-15c32c28ccc7.png)

**Comment by OdinGitDat** [comment] 2018-08-09 03:57
waiting eagerly for this project to become as good as shadowfox

**Comment by overdodactyl** [comment] 2018-09-03 01:36
There's definitely still a lot of work to be done with this project - hope to have a more finalized version out fairly soon though

**Comment by apaarfus** [comment] 2018-09-25 14:45
I can confirm this issue is also occurring on Windows 7x64, build 7601.
It should be noted I am also using Thunderbird 60.0

![image](https://user-images.githubusercontent.com/38731016/46021996-cc0cc980-c0af-11e8-8880-bdf75807ff15.png)

**Comment by OveR1337XD** [comment] 2018-10-08 21:52
So still nothing? 🤔

**Comment by overdodactyl** [comment] 2018-10-09 02:36
I've just uploaded a new version that's hopefully bug-free.  It doesn't style *everything*, but contains a large part of the UI.

I'll continue to add features as they are requested/as I have time.  

I'm going to go ahead and close this issue since there aren't any directly actionable tasks.

Anyone's welcome to open new issues, but they will get the quickest response if they are each limited in scope (i.e. a specific bug, a specific feature request etc.)

**Closed as completed by overdodactyl** 2018-10-09 02:36 UTC

**Comment by OveR1337XD** [comment] 2018-10-09 23:48
It's still not fixed! You should get Windows on the virtual machine to test it if you have a mac but it really looks bad!

![untitled](https://user-images.githubusercontent.com/3746977/46705132-7814ef80-cc2e-11e8-8d10-a2ccfcbbb11b.png)

And the file menu is bugged!

![untitled2](https://user-images.githubusercontent.com/3746977/46705145-82cf8480-cc2e-11e8-89e8-8e6db7920a29.png)

**Comment by overdodactyl** [comment] 2018-10-10 00:17
You're welcome to open new issues with specific bugs or features that can be addressed.  Leaving open an issue labeled "BUGGGSSS" isn't helpful for me or anyone looking to contribute.  

The issues in your screenshot seem to be OS dependent.  I don't currently have Windows and at this point I'm not too eager to install/pay for a VM.  

That being said, I'll gladly accept PRs from those who can and want to contribute, and I'll label any Windows-specific issues as such to hopefully get more targeted help.

**Comment by overdodactyl** [comment] 2018-10-10 15:15
See #3
